### PR TITLE
[1.x] Fix df20593 bug

### LINKED ISSUE #67: File not found after second request
Someone, please tell me what I am doing wrong 🤦 

I have a Laravel app that syncs references to files to the database to create a kind of, file explorer. This has been working fine but now I just can't get things to work. So after literally 3/4 hours of debugging and creating a completely fresh Laravel app with only this package installed (over and above the basics) and I've got this test code:

```
    $files = Storage::disk('google')->files('Renders/Bathroom');
    $file1 = [
        'file' => 'Renders/Bathroom/Bathroom with Black Fixtures.jpg',
        'exists' => Storage::disk('google')->fileExists('Renders/Bathroom/Bathroom with Black Fixtures.jpg')
    ];
    $file2 = [
        'file' => 'Renders/Bathroom/Blue and Grey Bathroom.jpg',
        'exists' => Storage::disk('google')->fileExists('Renders/Bathroom/Blue and Grey Bathroom.jpg')
    ];

    dd([
        'files' => $files,
        'file1' => $file1,
        'file2' => $file2,
    ]);

```

This is the output of the `dd`:

```
^ array:3 [▼
  "files" => array:9 [▼
    0 => "Renders/Bathroom/Bathroom with Black Fixtures.jpg"
    1 => "Renders/Bathroom/Blue and Grey Bathroom.jpg"
    2 => "Renders/Bathroom/Grey and Blue Bathroom.jpg"
    3 => "Renders/Bathroom/Loft Bathroom.jpg"
    4 => "Renders/Bathroom/Marble Bathroom.jpg"
    5 => "Renders/Bathroom/Modern Bathroom.jpg"
    6 => "Renders/Bathroom/Truffle Oak Bathroom.jpg"
    7 => "Renders/Bathroom/White Brick Bathroom.jpg"
    8 => "Renders/Bathroom/White Freestanding Bathroom.jpg"
  ]
  "file1" => array:2 [▼
    "file" => "Renders/Bathroom/Bathroom with Black Fixtures.jpg"
    "exists" => true
  ]
  "file2" => array:2 [▼
    "file" => "Renders/Bathroom/Blue and Grey Bathroom.jpg"
    "exists" => false
  ]
]
```

It seems that as soon as I call `Storage::disk('google')->fileExists('Renders/Bathroom/Bathroom with Black Fixtures.jpg')` once, then any subsequent requests to any other files are not found. To test this further, I simply switched the file paths for `$file1` and `$file2` and I get the same outcome, i.e:

```

    $files = Storage::disk('google')->files('Renders/Bathroom');
    $file1 = [
        'file' => 'Renders/Bathroom/Blue and Grey Bathroom.jpg',
        'exists' => Storage::disk('google')->fileExists('Renders/Bathroom/Blue and Grey Bathroom.jpg')
    ];
    $file2 = [
        'file' => 'Renders/Bathroom/Bathroom with Black Fixtures.jpg',
        'exists' => Storage::disk('google')->fileExists('Renders/Bathroom/Bathroom with Black Fixtures.jpg')
    ];

    dd([
        'files' => $files,
        'file1' => $file1,
        'file2' => $file2,
    ]);

...

^ array:3 [▼
  "files" => array:9 [▼
    0 => "Renders/Bathroom/Bathroom with Black Fixtures.jpg"
    1 => "Renders/Bathroom/Blue and Grey Bathroom.jpg"
    2 => "Renders/Bathroom/Grey and Blue Bathroom.jpg"
    3 => "Renders/Bathroom/Loft Bathroom.jpg"
    4 => "Renders/Bathroom/Marble Bathroom.jpg"
    5 => "Renders/Bathroom/ Modern Bathroom.jpg"
    6 => "Renders/Bathroom/Truffle Oak Bathroom.jpg"
    7 => "Renders/Bathroom/White Brick Bathroom.jpg"
    8 => "Renders/Bathroom/White Freestanding Bathroom.jpg"
  ]
  "file1" => array:2 [▼
    "file" => "Renders/Bathroom/Blue and Grey Bathroom.jpg"
    "exists" => true
  ]
  "file2" => array:2 [▼
    "file" => "Renders/Bathroom/Bathroom with Black Fixtures.jpg"
    "exists" => false
  ]
]
```

This is driving me bananas! Any help would be greatly appreciated!

Thanks,
Mat

### LINKED ISSUE #68: Unable to retrieve the file_size Error
Hello I got this issue 
League\Flysystem\UnableToRetrieveMetadata 

 Unable to retrieve the file_size for file at location: 2022-05-26-15-00-03.zip.

### LINKED ISSUE #70: directoryExists not defined
Hi,

Tried to check if folder exists to prevent multiple folders with the same name: 

```
if(!$fs->directoryExists($directory))
       $fs->createDirectory($directory, ['visibility' => 'private']);
```
but it throws an error. Am I trying something wrong? Tried with fileExists but doesnt work for directories.

undefined method League\Flysystem\Filesystem::directoryExists()

Thanks again!

### PR DESCRIPTION
**Pull request by erikn69**
Make df20593 optional, with option `useSinglePathTransaction`, this avoid problems and goes back to the old functionality

Closes #67
Closes #68
Closes #70

### CODE REVIEW

File: src/GoogleDriveAdapter.php [hunk 1]
```diff
@@ -496,7 +506,7 @@ public function copy($path, $newpath)
             if (isset($this->cacheHasDirs[$srcId])) {
                 $this->cacheHasDirs[$id] = $this->cacheHasDirs[$srcId];
             }
-            if ($this->useDisplayPaths) {
+            if ($this->useSinglePathTransaction && $this->useDisplayPaths) {
                 $this->cachedPaths[trim($newpathDir.'/'.$fileName, '/')] = $id;
```
Comment (masbug) [inline src/GoogleDriveAdapter.php:510]: cachedPaths should always be set in tandem with cacheFileObjects (and cacheHasDirs), otherwise virtual path resolution fails.

File: src/GoogleDriveAdapter.php [hunk 2]
```diff
@@ -1782,7 +1792,9 @@ protected function cachePaths($displayPath, $i, $indices, $parentItemId)
                 }
 
                 $query = $is_last ? [] : ['mimeType = "'.self::DIRMIME.'"'];
-                $query[] = "name = '{$token}'";
+                if ($this->useSinglePathTransaction) {
+                    $query[] = "name = '{$token}'";
```
Comment (masbug) [inline src/GoogleDriveAdapter.php:1796]: For the "many files" use case this should be reworked to mark the cache as incomplete and special care should be applied to toVirtualPath function and other functions accessing cacheFileObjects.
